### ISSUE TITLE
Unable to send out Qlink & another token....and gas from neo wallet......

### ISSUE THREAD

**Issue by soandrew2000** [CityOfZion/neon-wallet#699] opened 2018-02-14 11:18 UTC
as title.....what happen?
I tried to download and run from 0.07 to 0.13 latest ver......but still cannot send out.....and show "transaction failed" ..........Help !!

## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by mhuggins** [comment] 2018-02-19 15:28
Duplicate of #685.

**Closed by mhuggins** 2018-02-19 15:28 UTC

**Comment by Gibbo1066** [comment] 2018-02-20 07:26
Hi can anyone tell me the forum for NEP5 Neon wallet issues please? Thank you any send NEP5 hut have latest firmware. Thanks
