### ISSUE TITLE
Recipients from address book are shared over all wallets on same PC

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#947] opened 2018-04-07 19:09 UTC
Reproduction steps:
1. Create a new wallet (let's call it `Wallet A`)
2. Login to `Wallet A`
3. Click on `Send` button
4. Add new recipient to address book (let's call it `Recipient A`)
5. Logout
6. Create a new wallet (let's call it `Wallet B`)
7. Login to `Wallet B`
8. Click on `Send` button

After doing last step you can notice that recipients added on `Wallet A` are visible in address book on `Wallet B`.

Not a bug (that's how it was designed), adding it to keep track on it and to help prevent it from getting lost in the mix before v2 designs.

**Comment by comountainclimber** [comment] 2019-01-25 20:42
Closing this for now as the address book is currently set up this way by design

**Closed by comountainclimber** 2019-01-25 20:42 UTC
Labels: enhancement
