### ISSUE TITLE
I'm getting "could not retrieve DBC balance"

### ISSUE THREAD

**Issue by holgersindbaek** [CityOfZion/neon-wallet#480] opened 2018-01-05 11:26 UTC
I've send some DBC to my NEO address, but when I open the NEON app, it loads for a rather long time and then tells me that it "could not retrieve DBC balance".

What gives? Anyone else experiencing this?

**Comment by evgenyboxer** [comment] 2018-01-06 20:14
That could sometimes happen due to connectivity isssues. Could you retry opening the wallet? Does that happen again?

**Comment by holgersindbaek** [comment] 2018-01-06 21:23
It happens again and again.

I just updated to 0.0.9 and same story.

Could it have something to do with my Internet connection? Or is it the connectivity with the network you're talking about?

**Comment by Majinbooooo** [comment] 2018-01-07 03:36
I’m facing the same issue. On 0.0.7, by some luck, reopening the wallet multiple times i was able to get the NEO & GAS balance to show but most often not. On both 0.0.8 and 0.0.9, i am totally out of luck and is receiving “could not retrieve [all three newly added & NEO/GAS] tokens” error message followed by “Received latest blockchain information” but balance does not show. I’ve tried reinstalling the NEO ledger apps to v1.1.1, still does not work. I’m also receiving the “wallet is out of date” warning message even though after downloading the latest one 0.0.9

**Comment by MikeReining** [comment] 2018-01-09 16:56
I am having the same problem.  I am on 0.0.9.  I saw my DBC balance this morning.  I then pressed on "Claim x GAS".  After that is started showing the ERROR "could not retrieve DBC balance."  I have tried restarting my wallet multiple times without any luck.  Not sure what to do.  Don't mind HODL my DBC but sure would like to see it in the wallet.

**Comment by MikeReining** [comment] 2018-01-09 17:04
Quick update.  If I restart my wallet  and just keep it open it seems to briefly show my DBC balance and then it disappears again and I see the error message.  It keeps changing between these two states.  I never see the DBC balance long enough to be able to send it out.

**Comment by ccrypto12** [comment] 2018-01-09 17:10
I am having the same issue with the Neon wallet 0.0.9.  

This worked for me...
I took my Neon wallet private key and used it to open the wallet in neotracker.io and it worked just fine.  I can see my balances of GAS and DBC no problem, so for the time being I'll just use the web version instead of the desktop app.  Give them some time to update Neon.  
Hope this helps

**Comment by rtman** [comment] 2018-01-09 17:17
seeing the same issue here. Neotracker has all the right info tho.

**Comment by Mr-Tokk** [comment] 2018-01-09 17:49
I'm having the same problem. I'm on 0.0.9 version and still can't see my DBC balance . It just show the error message ''could not retrieve DBC balance.'' It appear for 2 sec and then disapear.

**Comment by galadril** [comment] 2018-01-09 18:00
Having the same issue after upgrading to 0.0.9

**Comment by a-mckinley** [comment] 2018-01-09 18:27
Same issue here after updating to 0.0.9.  Saw my DBC balance initially on upgrade and now seeing the error above, possibly after claiming GAS.

**Comment by webventurer** [comment] 2018-01-09 18:48
Same here. On 0.0.9 it keeps popping up with a red window saying "could not retrieve DBC balance". NEO and GAS numbers seem right.

**Comment by pyojaehun** [comment] 2018-01-09 18:51
Me too. Do not see the token information in the neon wallet now?

**Comment by pyojaehun** [comment] 2018-01-09 18:52
Me too.

**Comment by amckinley03** [comment] 2018-01-09 18:55
Same issue here after updating to 0.0.9. Saw my DBC balance initially on upgrade and now seeing the error above, possibly after claiming GAS.

**Comment by evan429** [comment] 2018-01-09 19:19
Same problem is happening with me... pretty frustrating to see none of my balance loading. Not my DBC is stuck without the ability to send to exchanges. Not operating up to what I expect from this team

**Comment by alexhawkins** [comment] 2018-01-09 19:52
Same, nothing loads for me. Stuck. When I switch from MainNet to TestNet, everything loads up but my balances are 0. Gas shows up briefly and then disappears.

**Comment by wildal** [comment] 2018-01-09 20:08
Same! 
could it be because of version 1.1.1?

**Comment by ikashi08** [comment] 2018-01-09 20:11
Same issue here. I hope this will be fix ASAP.

**Comment by chrisjohntapp** [comment] 2018-01-09 20:39
Same here, v0.0.9; it cycles through the DBC/RPX/QLC tokens (of which I have none) giving that same error for each. There is another possibly linked issue where my ledger S gets stuck on the 'wake up, neo', so I can't sign transactions and send neo.  This really needs resolving quickly.

**Comment by alexhawkins** [comment] 2018-01-09 21:10
Yeah, DBC on a nice run but if it starts to dip major and I can't get move my DBC off the Ledger to kucoin, you're costing me thousands of dollars. Not good guys.

**Comment by n8d** [comment] 2018-01-09 22:28
Same issue here. I tried the other explorer feeds and it was briefly working fine (as in no errors and my DBC balance was correct) with Antchain selected, but then it went back to throwing errors. Let me know if there is something I can do to help debug.

**Comment by Alex118** [comment] 2018-01-09 23:52
+1

**Comment by tubala** [comment] 2018-01-10 16:52
Same issue.

**Comment by boorac** [comment] 2018-01-10 17:51
Same issue here, neon v0.0.9 in conjunction with ledger nano s.

**Comment by danielkummer** [comment] 2018-01-10 21:09
+1

**Comment by JupJar** [comment] 2018-01-11 18:20
+1 with ledger nano s, scary

**Comment by jfuentep** [comment] 2018-01-11 19:00
+1 with ledger nano s

**Comment by Jorgen1970** [comment] 2018-01-11 20:27
PROBLEM SOLVED... at least for me...

I changed the Block Explorer to NeoScan... My tokens show up...

**Comment by Macspyre** [comment] 2018-01-11 22:05
+1 with ledger nano S which display "wake up Neo" and Neon 0.0.9 Mac Edition
Every 30 seconds, after each 'green wave animation' near "transaction history" title, there 3 error messages : 
"could not retrieve DBC balance"
"could not retrieve RPX balance"
"could not retrieve QLC balance"

If I click on a "i" button for DBC, RPX or QLC token, Neon interface becomes entirely white.
No other action is possible until I restart the app.

NEO transactions history : OK
NEO balance : OK

**Comment by fongstein** [comment] 2018-01-14 16:45
+1 same issues

**Comment by 4Eye** [comment] 2018-01-14 16:48
+1 same issues

**Comment by JupJar** [comment] 2018-01-14 17:19
.... no issue anymore for me ... all fine

**Comment by zafari2001** [comment] 2018-01-14 18:03
+1 same issue

**Comment by jfuentep** [comment] 2018-01-14 20:59
Solved also for me, it looks right now

**Comment by matthewgoodwin** [comment] 2018-01-15 05:03
same issue here... version v0.0.9

**Comment by Con7e** [comment] 2018-01-15 10:20
Same issue as @Macspyre please help fix it...

**Comment by MikeReining** [comment] 2018-01-16 20:06
Still having the same issue.  Sometimes the wallet appears to load fine but then the issue happens again.  Makes me scared to transfer DBC tokens into wallet.

**Comment by Allex1** [comment] 2018-01-18 12:35
+1

**Comment by mindlapse** [comment] 2018-01-20 17:59
+1

**Comment by Harsh87Shah** [comment] 2018-01-26 09:59
Same issue +1. I hope respected team is working on the fix.

**Comment by el1748eth** [comment] 2018-01-31 23:56
I can’t send my Qlc out of Neon. I was able to send out my DBC moments ago. The issue is that the QLC token does not appear in the drop-down. I see the tokens but cannot send QLC out. I have done everything I can think of. delete wallet on both ledger and the computer. downgrade to an earlier version, upgrade to latest 1.2. Erase cookies and reboot the computer. I have left a comment on a reddit post but I am at a lost.

**Comment by anfn101** [comment] 2018-02-11 22:18
There are occasional connectivity issues. You can check to see if the tokens are still in your address on Neotracker. Also note: Github is used to report code issues. Any support can be found in the Discord #support channel.

**Closed by anfn101** 2018-02-11 22:18 UTC
