### ISSUE TITLE
NEO GONE??

### ISSUE THREAD

**Issue by ph3l1x** [CityOfZion/neon-wallet#793] opened 2018-03-02 17:56 UTC
I just created an account and moved all my neo to the wallet. It was there last night. I wake up this morning and everything is gone??? Then for a split second I saw my neo in there and then it went back to 0 again.. There are 0  transactions.. What is happening? Where is my NEO at????

**Comment by mhuggins** [comment] 2018-03-02 19:06
Check the address on the blockchain (e.g.: neoscan).  If you see it on there, then it's fine.  It's possible the wallet is having connectivity issues.

**Comment by mhuggins** [comment] 2018-03-02 19:07
Closing this, as it's a duplicate of #792.

**Closed by mhuggins** 2018-03-02 19:07 UTC
