### ISSUE TITLE
My Neo Wallet 0.2.3 is not letting collect gas and is acting frozen for almost a day. Please help.Thankyou

### ISSUE THREAD

**Issue by Cowboyup77** [CityOfZion/neon-wallet#1032] opened 2018-04-29 19:26 UTC
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by mhuggins** [comment] 2018-04-29 19:31
Duplicate of #1028.

**Closed by mhuggins** 2018-04-29 19:31 UTC

**Comment by Olorunsola2** [comment] 2018-05-26 05:29
Similar situation here. No solution? Plenty of GAS is owed to my account
