### ISSUE TITLE
I did not receive my coins on my wallet

### ISSUE THREAD

**Issue by mharw** [CityOfZion/neon-wallet#87] opened 2017-08-11 20:03 UTC
Hello. 
Today I sent 3 (three) NEO coins to the address AUsf7BE2YLGyAdoc3kQTfMW7MH7ggtiKrm (purse NEON), and coins have not yet come to me. 
What should I do? 
Thank you. (Sorry, I do not speak English and Chinese. Translate Google) 
!

**Comment by canesin** [comment] 2017-08-11 20:22
This is a version issue (please uninstall it and use this one: https://github.com/CityOfZion/neon-wallet/releases/download/0.0.3c/Windows.Neon.Setup.0.0.3.exe)

**Comment by mharw** [comment] 2017-08-11 20:48
Спасибо, но именно эту версию я и инсталлировал. Balance 0. ((

**Comment by mharw** [comment] 2017-08-11 20:50
I just bought NEO for the first time and first installed the purse NEON. More precisely, yesterday.

**Comment by canesin** [comment] 2017-08-11 20:51
the 0.0.3c ? It is different than the 0.0.3 ...

**Comment by mharw** [comment] 2017-08-11 20:58
I did as you said, but the balance also shows 0. Also I checked the links, today I downloaded the same version that you gave me now.

**Comment by mharw** [comment] 2017-08-11 21:01
Может у вас ссылки неправильные? Я сейчас заглянул в свойства приложения, там написано 0.0.3.

**Comment by canesin** [comment] 2017-08-11 21:03
No, it is correct ..this is because the author didn't increase the version number .. On the print screen it says "refreshing"on the top green bar .. is this permanent ?

**Comment by mharw** [comment] 2017-08-11 21:07
Approximately, from 1 minute to 10. And even more. I press all the time, hoping that the balance will change, but the balance does not change. I do not even know if I should press this button at all.

**Comment by canesin** [comment] 2017-08-11 22:34
Thanks @mharw , I`m reopening this issue .. but keep this private keys safe. As you could see from the explorer your tokens are safe.

**Comment by mharw** [comment] 2017-08-11 23:01
Thank you! I'll wait for the solution!

**Comment by Ejhfast** [comment] 2017-08-11 23:43
@mharw any update? we were getting a period of heavy load a few hours ago, could that have been the problem?

**Comment by mharw** [comment] 2017-08-12 08:43
I do not know what the problem is. Look at the picture, first I downloaded the link that is in the picture. Then, by the link given by "canesin", the link is exactly the same. At the moment the problem remains.
![03](https://user-images.githubusercontent.com/30937992/29239265-2f4f4ce0-7f64-11e7-861d-2e09853cd343.png)

**Comment by 60168** [comment] 2017-08-13 21:18
How do I buy NEO and where to buy? Thank you.
My email is eosokk007@gmail.com

**Comment by mharw** [comment] 2017-08-13 21:29
https://www.binance.com/trade.html?symbol=NEO_BTC
https://19800.com/market/cny_ans/

**Comment by cdncoin1962** [comment] 2017-08-14 12:26
I'm using Neon Wallet .3 ...I've had bits of coins and full coins not show up in Neon wallet. This appears to be an ongoing issue that isn't being resolved. I just sent 4 coins to the wallet, only 3 showed up. At $50US a coin, that is too much money for me to put anymore trust into this wallet until this is fixe. Especially when I tried to scan my address on the blockchain explorer and I receive a message back stating it can't be found. Starting to think I'm being scammed. 

If I'm wrong, please clearly explain what the issue is.

**Comment by stevesbrain** [comment] 2017-08-14 12:44
@cdncoin1962 - I don't see how this is possible (in terms of it being a fault of the wallet). All "transactions" are simply a cryptographic process. Someone sends you coins, they're basically signing a message with their private key that transfers X to your public key. Simple as that. There is not "partial" transfer (as in, coins don't go missing). However, what I have seen is people having issue with transferring from their exchange.

For example, Neo can only be transferred in "whole" numbers. You can't transfer part of a NEO. So if an exchange charges a fee for withdrawing, and you withdraw 4 NEO, then after deducting the fee, you are really only trying to withdraw 3.75 NEO. When you try to withdraw 3.75 NEO, only 3 get withdrawn, and the other .75 either are discarded, or returned to the exchange (depending on which exchange you do this through).

So, for example, if you wanted to withdraw 4 NEO, you should really withdraw 4 NEO + withdraw fee (i.e. 4.35 NEO in order to receive all NEO). You can confirm this by checking the transfer to your address - if it only shows 3 NEO, nothing else, then you can be fairly sure that this is what's happened. Does that sound about right?

**Comment by cdncoin1962** [comment] 2017-08-14 12:58
No it doesn't sound right. My exchange is withdrawing their fee, then
transferring the rest. Whoever is mining, or confirming the transaction
prior to deposit is doing the rounding down and only depositing the 3,
rather than 3.9, or as you stated 3.75. The rest is going into someones
pocket. It's not going back to the exchange, or back into my account. I
will find out who is doing this!

**Comment by cdncoin1962** [comment] 2017-08-14 13:30
I found out where my missing coin is going.
Whoever is at address: AR4QmqYENiZAD6oXe7ftm6eDcwtHk7rVTT is collecting the
bits. So far, 3.9469578 of my NEO coins have been stolen by the owner of
that address.

I want them back. They can be deposited to my NEO wallet at this address:
AcPre1KPG9z3LBKCZ1N5U6JTVXijCwjxCf

**Comment by cdncoin1962** [comment] 2017-08-14 13:49
Here's the backup info to show where my coins are going.

**Comment by cdncoin1962** [comment] 2017-08-14 14:32
Whoever is at Address     AR4QmqYENiZAD6oXe7ftm6eDcwtHk7rVTT   is collecting a lot of peoples coin fractions.
<img width="577" alt="screen shot 2017-08-14 at 11 08 33 am" src="https://user-images.githubusercontent.com/31006174/29276192-2f60667a-80e4-11e7-92de-db1386617582.png">

**Comment by cdncoin1962** [comment] 2017-08-14 14:33
Because it doesn't appear above....here is the backup to my claim that address AR4QmqYENiZAD6oXe7ftm6eDcwtHk7rVTT    has my missing coins.

<img width="919" alt="screen shot 2017-08-14 at 10 47 54 am" src="https://user-images.githubusercontent.com/31006174/29276269-67c8c5ca-80e4-11e7-99de-3dde91aa4339.png">

**Comment by cdncoin1962** [comment] 2017-08-14 14:35
@canesin ....I hope you get to the bottom of this and have peoples missing coins returned to them.

**Comment by cdncoin1962** [comment] 2017-08-14 14:36
@canesin ....your credibility is on the line.

**Comment by cdncoin1962** [comment] 2017-08-14 14:40
I've now transferred all my NEO out of this wallet and will not be transferring any back in. If my missing/stolen NEO ever are returned, please return to this address
Aa941RkYw8WVidtXKCWChtbnBYcSymGZmN.

**Comment by cdncoin1962** [comment] 2017-08-14 14:56
@canesin ....your profile states you are in Cambridge, MA. Seeing how you are the owner and created this wallet, you are responsible. I certainly hope, for your sake,  you are not the owner of the address receiving peoples deposits & skimming off the fractions because that is called fraud, theft, etc....and USA has laws against that. If you have a contract with this address, then you need to have a strong conversation to ensure people receive their coins back. 

I recommend you look into the matter, send out a message stating you've found the issue and will be ensuring everyone receives their coins back. Before someone sends all of this to the FBI.

**Comment by lucianoengel** [comment] 2017-08-14 14:56
@cdncoin1962 I'm sorry for your lost coin, but NEON is not to blame for that. This address times out because it has so many transactions that most explorer can't handle it. I've built NeoScan so I know these address as they heavily load the servers. There's not many addresses like that in the chain and my guess is they are all from exchanges, since they are the ones doing most of the transactions. Anyway, you can always check the code and verify yourself that NEON has nothing to do with this. Again, I am sorry for your lost coin, but please stop threatening people and insisting on blaming CoZ for that. This is a known issue and I don't understand why you try so hard to focus your anger in us instead of going after the exchange that is stealing you. Best Wishes

**Comment by cdncoin1962** [comment] 2017-08-14 15:05
The exchange is not stealing. The exchange is sending what they are suppose to send just as they do with every other coin. It is ONLY with the transfer to THIS wallet where the problem is. If you KNOW that address, then you KNOW who it belongs to and who has the coins. Does the address belong to NEON, or does it belong to the exchange? You set it up, you tell me.

**Comment by canesin** [comment] 2017-08-14 15:13
@cdncoin1962 this has nothing to do with CoZ, NEON wallet or myself.

**NEO cannot be transact in fractions, NEO is indivisible**

The exchange your are using must be Bittrex, they allow people to transact in fractions and withdraw in fractions, but the network will refuse such transaction. So bittrex get your amount, deducts their fare and send only the interger part:
RECEIVING_AMOUNT = Int(your_withdraw - fare).
So for example if you send 3.5 you will receive 3:
3 == int(3.5 - 0.35)
Please read this before coming here and disturbing the development because you are poorly informed: https://www.reddit.com/r/NEO/comments/6su31n/here_are_some_things_you_should_know_if_you_are/

**This is a know problem of Bittrex and I'm so tired of this and getting my name involved with suck a poor design even not having -1% involvement in it  that I'm ANNOUNCING right now that I will do a exchange system that don't steal people**

@cdncoin1962 that address can only be from the exchange, NEON HAS NO ADDRESS NOR DOES IT HAS A SEND SERVER, NOR DOES IT STORE KEYS, NOR DOES IT HAS THE ABILITY TO SEND ANYTHING BY ITSELF.

**Closed by canesin** 2017-08-14 15:13 UTC

**Comment by cdncoin1962** [comment] 2017-08-14 15:20
Thank you for your quick response. I am determined to get to the bottom of this.

**Comment by canesin** [comment] 2017-08-14 15:22
@cdncoin1962 
Please do, I have lost too much time on this already:
https://steemit.com/cryptocurrency/@dwongch/antshare-neo-exchange-tx-fee-bittrex
https://www.reddit.com/r/NEO/comments/6s2ttd/bittrex_transfer_fee_is_now_01_ans/
