### ISSUE TITLE
Trinity (tnc) not showing balance

### ISSUE THREAD

**Issue by meyerchak** [CityOfZion/neon-wallet#688] opened 2018-02-13 05:02 UTC
Neon wallet 0.1.2
Nano Ledger s 1.3.1

The trinity (tnc) balance is not showing on neon wallet. 
Transferred trinity from kucoin exchange to neon wallet through ledger nano s. 
The transaction shows on the blockchain. Kucoin confirms. 

Please update neon wallet for trinity (tnc) neo coins

Thank you

**Comment by mhuggins** [comment] 2018-02-13 05:09
Duplicate of #662.

**Closed by mhuggins** 2018-02-13 05:10 UTC

**Comment by meyerchak** [comment] 2018-02-13 07:16
thank you. 
hash for trinity. Then it showed up in the wallet next to the other four coins with my balance in there 

Thanks for your help
