### ISSUE TITLE
Wallet crashes on dashboard if one of cryptocompare `histohour` responses fail to respond

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1677] opened 2018-11-12 14:30 UTC
**Wallet version or commit SHA:**
`dev` branch (ee7f579)

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.376

**Reproduction steps:**
1. Start wallet
2. Set intercepting on `https://min-api.cryptocompare.com/data/histohour?limit=24&fsym=GAS&tsym=USD` or `https://min-api.cryptocompare.com/data/histohour?limit=24&fsym=NEO&tsym=USD`
3. Login to the wallet
4. Pass all requests excluding the one mentioned above

**Description:**
If one of these two requests fail to respond (or both of them):
`https://min-api.cryptocompare.com/data/histohour?limit=24&fsym=GAS&tsym=USD`
`https://min-api.cryptocompare.com/data/histohour?limit=24&fsym=NEO&tsym=USD`
Wallet is crashing on dashboard. This means that currently we're fully relying on cryptocompare API in the wallet (by this I mean that if this endpoint goes down, wallet will crash on login).

**Video:**
![neon_crash](https://user-images.githubusercontent.com/8177587/48353530-f16d8b00-e68f-11e8-8131-e6f0d31f2be2.gif)

There are 3 different console errors in 3 cases:
1. Both of requests fail to respond
2. Request for `histohour` GAS fail to respond
3. Request for `histohour` NEO fail to respond

**Comment by comountainclimber** [comment] 2018-11-12 16:02
I am unable to reproduce this using the exact steps you outlined on macOS

**Comment by comountainclimber** [comment] 2018-11-12 16:09
![attempt-to-repro-on-osx](https://user-images.githubusercontent.com/13072035/48359665-abe29b00-e65a-11e8-9b10-a5006ab5db29.gif)

**Comment by comountainclimber** [comment] 2019-02-25 00:55
Fixed in 2.1.0

**Closed by comountainclimber** 2019-02-25 00:55 UTC
Labels: bug, high impact
