### ISSUE TITLE
wallet stuck on loading screen when starting up. Wallet was previously working fine.

### ISSUE THREAD

**Issue by sendmacro** [CityOfZion/neon-wallet#1169] opened 2018-06-02 09:17 UTC
**Wallet version or commit SHA:**
0.2.4 and 0.2.5

**Environment:**
Win 7 64bit

**Prerequisites:**
wallet stuck on loading screen when starting up. Wallet was previously working fine.

**Reproduction steps:**
 Restarted pc and tried to open neon wallet. Same issue occured.
 uninstalled the wallet and removed neon folder from app data/roaming
 reinstalled neon 0.2.4 and tried to open. Wallet still not loading
 uninstalled the wallet and removed neon folder from app data/roaming
 installed neon 0.2.5 and tried to open. Wallet still not loading

![untitled](https://user-images.githubusercontent.com/39852934/40872883-974cffe6-6699-11e8-87d7-fe7088f60d44.png)

**Comment by drptbl** [comment] 2018-06-02 17:32
Caused by #1128. Will be fixed in next release. Please re-open if not. Thanks.

**Closed by drptbl** 2018-06-02 17:32 UTC
