### ISSUE TITLE
Sending NEP-5 tokens transaction failed release 0.0.8

### ISSUE THREAD

**Issue by BIMEnergy1978** [CityOfZion/neon-wallet#466] opened 2018-01-04 09:16 UTC
Sending nep-5 tokens with ledger does not work. transaction failed release 0.0.8

**Comment by Derkvanderwoude** [comment] 2018-01-04 09:45
I get the same error with sending NEP-5 Tokens. Latest firmware release 1.3.1

**Comment by willtc** [comment] 2018-01-04 10:08
Same error here, but it seems only to be happening with large amounts (>30000) of tokens.
-Transferrring 10 RPX and 500 RPX went OK

**Comment by BIMEnergy1978** [comment] 2018-01-04 10:10
Here it doen not even work with 1 token RPX or DBC

**Comment by Derkvanderwoude** [comment] 2018-01-04 10:20
Same error even with small amount (<100) NEP-5 Token (DBC)

**Comment by valdor27** [comment] 2018-01-04 10:22
If you are using a Ledger device with Neon make sure to update the Ledger app or transactions will fail !

Is your Ledger up to date ?

**Comment by Derkvanderwoude** [comment] 2018-01-04 10:24
Ledger version 1.3.1 and Neon version 0.0.8.
Even sending Gas fails

**Comment by BIMEnergy1978** [comment] 2018-01-04 10:26
me to

**Comment by BIMEnergy1978** [comment] 2018-01-04 10:28
i got it..... delete the application on your ledger and reinstall it......

and the the magic hapens

**Comment by Derkvanderwoude** [comment] 2018-01-04 10:32
Yes solved the problem :-) thanks

**Comment by Ejhfast** [comment] 2018-01-04 16:03
I will leave this issue open so that others can see it, but you need to update your ledger software for NEP5 sending to work

**Comment by Kmpec** [comment] 2018-01-04 17:18
Hey there, I was trying to send RPX with the Neon 0.0.8 Wallet. However it says the transaction was successfull, but it doesnt show up. Only if I do it with smaller amounts (4.000 RPX) it worked. I accessed the wallet via private key, not with a ledger.

**Comment by mhuggins** [comment] 2018-01-04 22:21
Thanks for reporting. @dvdschwrtz found the cause and is working on a fix. Stay tuned.

**Comment by C3KTAHT** [comment] 2018-01-04 22:27
Thanks!

**Comment by Losakoa** [comment] 2018-01-05 05:55
Holding DBC in Neon Wallet.  Tried to send it back to exchange with Ledger Nano S from Neon Wallet.  I get success pop up and that I will be updated with the newest blockchain, but the balance doesn't change.

I've removed NEO app with app manager and reinstalled it.  Still doesn't send.

**Comment by mvg-tinus** [comment] 2018-01-06 11:14
Version 0.0.9 does not seem to have fixed the issue unfrotunately.

**Comment by robertohegeler** [comment] 2018-01-08 07:28
I have the same issue. Newest Ledger Nano app and 0.0.9... I can not send any tokens and also not NEO. All do not work, I can only receive. What to do?

**Comment by badgerwithagun** [comment] 2018-01-08 23:06
Same problem here.  Looking at the transactions NEON is posting on neotracker.io, we have:

* -0.00000001 GAS from my public key
* +0.00000001 GAS to my public key
* An invocation script
* No transfer details (which is what I see normally when I do a NEP-5 transfer)

In addition, there were no transfer details shown on the Ledger screen during signing. I would have stopped right there, but this is rather urgent.

The only workaround I can think of is to extract the WIF from the seed phrase on an offline machine then use NEO-GUI.

Personally, I'm hoping not to have to go there, since it's impossible to do offline transactions with NEO as far as I can tell, which means the public key will be on an internet connected machine.  However, I may be forced to.

**Comment by pyojaehun** [comment] 2018-01-09 15:21
I have the same problem. When I send 10000DBC, I only send a small amount of gas, and DBC does not move. Also, when I sent 100DBC, 100DBC disappeared from my wallet. The transaction is being delayed by NOT FOUND 404.

**Comment by pyojaehun** [comment] 2018-01-09 15:27
I have the same problem. When I send 10000DBC, I only send a small amount of gas, and DBC does not move. Also, when I sent 100DBC, 100DBC disappeared from my wallet. The transaction is being delayed by NOT FOUND 404.

**Comment by derwen** [comment] 2018-01-09 16:03
"I have the same problem. When I send 10000DBC, I only send a small amount of gas, and DBC does not move. Also, when I sent 100DBC, 100DBC disappeared from my wallet. The transaction is being delayed by NOT FOUND 404."

Exactly the same problem.

**Comment by RobinHeld** [comment] 2018-01-09 16:07
https://neotracker.io/tx/f142f6f5548dd4c408cdf757f960efe7ec598a975a167228e16126e6f27d89e2

Same issue. No tokens being sent, just a strange transaction with the smallest denomination of gas.

**Comment by mhuggins** [comment] 2018-01-09 16:11
Unfortunately NEO Tracker is not showing the tokens transferring when these invocation transactions are created, and so you cannot verify whether a transaction succeeds based upon that.  Just to verify, are you still seeing the same amount of DBC in your wallet before and after the transaction is added to the blockchain?

**Comment by RobinHeld** [comment] 2018-01-09 16:12
QLC transaction, and yes, I've been trying to send it for some time now.
Still remains.

**Comment by RobinHeld** [comment] 2018-01-09 16:13
https://neotracker.io/tx/c63b0c77ed0ca69c2901ff795ebfb76e1ce3d837bd2092f9d56e13086b4e0c6e

This earlier transaction shows the token transfer at the foot of the page,
FYI. So I assume something is going wrong, as this worked before.

**Comment by derwen** [comment] 2018-01-10 13:21
Any amount under 1000 goes through. The problem has to be rooted somewhere connected with decimal places in numbers. Please fix it and release a new Neon as soon as possible.

**Comment by badgerwithagun** [comment] 2018-01-10 15:48
It's not quite so simple by the sound of things. I had to make a 999 transfer, and after that, transfers of any amount worked fine.

**Comment by mhuggins** [comment] 2018-01-10 15:57
I'm curious for the users having trouble.  Are your thousands formatted like "1,000" or "1.000"?

**Comment by RobinHeld** [comment] 2018-01-10 16:07
I'm trying to send under 1000 QLC and still having no joy.

**Comment by mvg-tinus** [comment] 2018-01-10 19:02
Even sending 20 units of GAS is not possible.

**Comment by mvg-tinus** [comment] 2018-01-10 19:08
At the moment, claiming GAS does not work either. Transaction Error message.

**Comment by caizhiyuanrise** [comment] 2018-01-10 19:23
So, if you hit "claim Gas" wait until the transaction is in the next block. Otherwise it does not work to send anything. (on my side)
Deleting the NEO app on the Ledger Nano S and reinstalling and having 0.0.9 works fine for me, after I waited for the next block and I do not use a ,...

**Comment by mvg-tinus** [comment] 2018-01-10 19:26
I reinstalled the NEO app on the ledger and now claiming GAS works fine.

**Comment by cryptoking333** [comment] 2018-01-22 12:12
did anybody solve this i have updated to the new version 0.1 and cant claim gas or send neo just get a transaction failed doesn't even ask me to verify on the Ledger. Yesterday i signed the transaction but money didn't leave 24 hours later nothing is sent

**Comment by anfn101** [comment] 2018-02-11 22:08
Try version 0.1.2

**Closed by anfn101** 2018-02-11 22:08 UTC
Labels: nep5
