### ISSUE TITLE
Wallet requests `index.html` for balances instead of RPC nodes if cryptocompare `/data/pricemultifull` or neoscan `get_unclaimed` or github `/releases/latest` request fail to respond

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1678] opened 2018-11-12 14:47 UTC
**Wallet version or commit SHA:**
`dev` branch (ee7f579)

**Environment:**
Win 10 Home (64 bit) Version 1803 Build 17134.376

**Reproduction steps:**
1. Set intercepting on `https://min-api.cryptocompare.com/data/pricemultifull?fsyms=<shortened>&tsyms=USD` or `https://api.neoscan.io/api/main_net/v1/get_unclaimed/<addr>` or `https://api.github.com/repos/CityOfZion/neon-wallet/releases/latest`
2. Start wallet
3. Login to the wallet
4. Pass all requests excluding the one mentioned above

**Request:**
```
https://min-api.cryptocompare.com/data/pricemultifull?fsyms=%00,ACAT,APH,APT,ASA,AVA,BCS,BDN,CGAS,CGE,CGL,COUP,CPX,DAD,DBC,EDS,EFX,EPN,EXT,FTW,GALA,GDM,GTA,GUARD,IAM,JWT,LRN,LX,MCT,NEX,NKN,NNC,NOS,NRVE,NVL,OBT,ONT,PEGCNY,PEGUSD,PHX,PKC,PROQ,QLC,RHT,SCC,SDS,SDT,SENNO,SGAS,SGT,SOUL,SPOT,SWH,SWTH,THOR,TKY,TNC,TOLL,UTD,WWB,XQT,XQTA,YEZ,ZPT,DBC,RPX,QLC,NEO,GAS&tsyms=USD
```
```
https://api.neoscan.io/api/main_net/v1/get_unclaimed/<addr>
```
```
https://api.github.com/repos/CityOfZion/neon-wallet/releases/latest
```

**Description:**
If request mentioned above is dropped, wallet tries to do invokes for balances to `index.html` instead of RPC nodes.

**Video:**
![neon_rpc_issue](https://user-images.githubusercontent.com/8177587/48354499-34c8f900-e692-11e8-818a-a4ec59b0ae23.gif)

**Comment by comountainclimber** [comment] 2018-11-12 16:02
I am unable to reproduce this using the exact steps you outlined on macOS

**Comment by comountainclimber** [comment] 2018-11-13 03:07
Fixed in https://github.com/CityOfZion/neon-wallet/releases/tag/2.0.0

**Closed by comountainclimber** 2018-11-13 03:07 UTC
Labels: bug, design-v2
