### ISSUE TITLE
Can't send: Error occurred in handler for 'safeStorageEncrypt': Error: Error while decrypting the ciphertext provided to safeStorage.decryptString. Encryption is not available.

### ISSUE THREAD

**Issue by manuel-arguelles** [CityOfZion/neon-wallet#2461] opened 2023-01-16 22:44 UTC
I get this constant console error: `Error occurred in handler for 'safeStorageEncrypt': Error: Error while decrypting the ciphertext provided to safeStorage.decryptString. Encryption is not available.` which doesn't allow much usage of the app.

**Wallet version or commit SHA:**
2.16.16

**Environment:**
Linux Ubuntu 20.04.5 (Neon.2.16.16.AppImage)

**Prerequisites:**
I'm using it with a ledger device.

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Ledger" button
3. Click on "Login" button
4. Click on "Send" button

Screen dies and the terminal gets flooded with:
```
Error occurred in handler for 'safeStorageEncrypt': Error: Error while decrypting the ciphertext provided to safeStorage.decryptString. Encryption is not available.
    at /tmp/.mount_Neon.2lBmt3n/resources/app.asar/main.js:274:30
    at node:electron/js2c/browser_init:189:579
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:11327)
    at EventEmitter.emit (node:events:526:28)
```

**Comment by manuel-arguelles** [comment] 2023-01-16 22:45
There's something similar reported for electron: https://github.com/electron/electron/issues/32598

**Comment by HodeiG** [comment] 2023-02-27 14:58
Same issue in **Debian 11** with `Neon.2.16.29.deb`

**Comment by HodeiG** [comment] 2023-02-27 15:19
It looks like this issue was introduce as part of this commit:
https://github.com/CityOfZion/neon-wallet/commit/3c1d294310c92482443bd468d6d4a72c0d2b0836

A temporary workaround could be to downgrade to `Neon.2.12.11`

**Comment by comountainclimber** [comment] 2023-02-27 17:47
@HodeiG @manuel-arguelles thanks for reporting this and sorry for the delay will be implementing a solution to this issue in the next release

**Comment by comountainclimber** [comment] 2023-03-15 17:33
OK @HodeiG and @manuel-arguelles finally got to the bottom of this issue (took a little while) and was able to reproduce

The root of this problem is due to the fact that Neon is unable to access the operating system's login secret which we use to encrypt the contacts file.

If you open the [Gnome Keyring](https://en.wikipedia.org/wiki/GNOME_Keyring) and unlock login passwords this will allow Neon access to the secret used to encrypt the files and fix the problem.

The next time you open Neon should "just work"!

**Comment by comountainclimber** [comment] 2023-03-15 17:33
Going to leave this open for now but if this fixes the problem, which I believe it should, please close the issue

**Comment by HodeiG** [comment] 2023-03-15 18:05
hi @comountainclimber, thank you for taking the time to look into this. In my system `gnome-keyring` wasn't installed, so I think the deb package should consider this dependency.

Although I installed the dependency, I am not quite sure how the gnome-keyring can be setup to `unlock login passwords` as I am using i3wm as a the main window manager. I tried to start the gnome-keyring-daemon in the command line as explained in [here](https://askubuntu.com/a/1305220/1667665) but that didn't resolve the issue for me. Any advice?

**Comment by comountainclimber** [comment] 2023-03-15 20:03
@HodeiG I am a total Linux novice but you shouldnt need to install anything and `gnome-keyring` is NOT a dependency of neon-wallet

This is the screen on ubuntu I used to reproduce the issue you are describing and is exactly what I would expect if Neon does not have access to the key (ignore the arrows and numbers in this image):
![image](https://user-images.githubusercontent.com/13072035/225429270-2c652681-72fb-4b0d-a2aa-e5a52f33f141.png)

**Closed as completed** 2023-03-22 20:41 UTC
Labels: High
