### ISSUE TITLE
Nano ledger S + NEON wallet: no transactions possible

### ISSUE THREAD

**Issue by horadriccube** [CityOfZion/neon-wallet#790] opened 2018-03-02 14:32 UTC
Latest update of Nano ledger + latest update of Neon wallet. My funds are now stuck, cant claim gas either. Upon signing Tx I get a error message. 

Guys please help me out here.

**Comment by cassady32** [comment] 2018-03-02 15:00
I am also having the same issue.  Tried claiming gas, transaction froze and claim never happened.  Have tried claiming gas / transferring from the wallet without success.  Gas is also no longer accruing and is frozen at the previous amount.  Please help.

**Comment by knadkicker1** [comment] 2018-03-02 15:01
Glad it's not just me, especially when $$$$ is on the line

**Comment by knadkicker1** [comment] 2018-03-02 15:02
Also, not updating block number even though refreshing says updated

**Comment by cassady32** [comment] 2018-03-02 15:04
Same.  Stuck at the same block after refresh.

**Comment by Merde2001** [comment] 2018-03-02 15:10
Same here : transaction failed! I can’t neither claim gas, nor send me neo. Gas isn’t accumulating.
The only difference is that I don’t use Nano S

**Comment by Omegshi147** [comment] 2018-03-02 15:11
I have the exact same problem. Tried reinstalling the wallet, tried reinstalling the NEO app, nothing is working.

**Comment by Merde2001** [comment] 2018-03-02 15:11
Can we contact the company so they fixed the problems?

**Comment by knadkicker1** [comment] 2018-03-02 15:15
I don't think its a company that develops the wallet. Sort of like how MEW works.

**Comment by Merde2001** [comment] 2018-03-02 15:20
That sucks! What if NEO crashes and we can’t even sell?
I will never use Neon wallet again! 
There are much better ways of doing this on the web, those guys never experience any issues. Everything is nice and smooth like MEW

**Comment by Omegshi147** [comment] 2018-03-02 15:21
Neither Neon wallet nor the NEO blockchain would crash down, thats not how blockchain works.

**Comment by Omegshi147** [comment] 2018-03-02 15:23
Anyways, did you guys all have this problem today? I want to know if this is an unique issue that I can't just search up the answer to and that someone has solved before.

**Comment by Omegshi147** [comment] 2018-03-02 15:25
Even though I'm hodling this is a bit concerning.

**Comment by knadkicker1** [comment] 2018-03-02 15:26
Neo is down officially. Last block was generated over an hour ago and some nodes are offline https://neotracker.io/

**Comment by Merde2001** [comment] 2018-03-02 15:27
I never had this issue before. 
Are u guys using Version 0.1.4?

**Comment by Omegshi147** [comment] 2018-03-02 15:28
Ouch wait so NEO blockchain is actually down

No wonder my GAS isn't generating

**Comment by knadkicker1** [comment] 2018-03-02 15:28
Food for thought: Supposedly Neo can NEVER be forked, which means your funds are there. Neon Wallet DOESN'T hold the funds. You own your private keys, especially if you use a Ledger.

**Comment by Merde2001** [comment] 2018-03-02 15:29
Wow anyone has any clue of what happened eith NEO Blockchain?

**Comment by JupJar** [comment] 2018-03-02 15:30
NEON WALLET --- NOTHING WORKS ANYMORE


1.) Claiming GAS
clicked, confirmed on Nano S, --error message
![image](https://user-images.githubusercontent.com/35327533/36906565-cb0af01e-1e68-11e8-9161-df22304a1824.png)

2.) Sending GAS
Asked to confirm, disappears in seconds (couldn't confirm) -- Transaction Error

**Comment by Omegshi147** [comment] 2018-03-02 15:31
Everyone is having this issue, stop screaming

**Comment by Omegshi147** [comment] 2018-03-02 15:31
Even sending it has issues

**Comment by knadkicker1** [comment] 2018-03-02 15:32
Because the entire Neo blockchain has been halted. No one can do anything

**Comment by Omegshi147** [comment] 2018-03-02 15:44
It's working now guys. Try again.

**Comment by Omegshi147** [comment] 2018-03-02 15:44
That was a quick response time to an issue tbh

**Comment by JupJar** [comment] 2018-03-02 15:53
Claiming GAS works for me now too.
Sending still bringing up "Error  Transaction failed"

**Comment by Merde2001** [comment] 2018-03-02 15:58
Sending works perfectly for me now. Just sent it to binance

**Comment by Merde2001** [comment] 2018-03-02 16:11
Just sent 1 to binance and it worked!
Tried to send the rest and it didn’t work. But now it’s all gone!

**Comment by JupJar** [comment] 2018-03-02 16:15
Unfortunately not for me (wanted also to send GAS to Binance)
(MAC, Nano S, Nano Wallet 0.1.4)
![image](https://user-images.githubusercontent.com/35327533/36908877-26b3f9aa-1e6f-11e8-85e2-0fa6962e2e0b.png)

After "Send Asset" clicked
![image](https://user-images.githubusercontent.com/35327533/36908936-4af56bfa-1e6f-11e8-804a-9527e369e292.png)

Nothing happened on the Nano display.
after 2 seconds, again ...
![image](https://user-images.githubusercontent.com/35327533/36909032-8777b4a2-1e6f-11e8-846d-736e1ec3b7ee.png)

**Comment by JupJar** [comment] 2018-03-03 11:45
Fine for me now. Could send GAS today.

**Comment by Rvv365** [comment] 2018-03-05 12:23
Hello, was about to transfer. Wondering if safe to do now.

**Comment by Niels1990** [comment] 2018-03-06 06:14
I can't send NEP 5 tokens from my Ledger, what to do????

**Comment by Omegshi147** [comment] 2018-03-06 06:49
Wait for several minutes. It has a bit of a bug in generating blocks.

**Comment by Omegshi147** [comment] 2018-03-06 06:50
It should work now, blocks are back up and running.

**Comment by Cryptonnyx** [comment] 2018-03-06 12:03
Nope, got it agian now. ffs

**Comment by Alotoffixins** [comment] 2018-03-07 11:35
Why hasn't this issue been fixed yet, if we cant make transactions then this wallet is effectively useless!

**Comment by danpan8** [comment] 2018-03-08 22:31
I'm getting the transaction failed error also when trying to claim Gas on Neon 0.1.4, was working fine until today. Any ideas?

**Comment by sbglive** [comment] 2018-04-01 08:42
I am still having the same issue. Has anyone found a workaround ? It has been like this for months on my side, regretting the decision to support what seemed like a promising network with my money. Instead it feels like a scam.

At least the team could have the decency to reply or give us a clue ?

**Comment by mhuggins** [comment] 2018-04-29 19:47
Tracking this issue under #882.

**Closed by mhuggins** 2018-04-29 19:47 UTC
