### ISSUE TITLE
Can't claim GAS

### ISSUE THREAD

**Issue by Fossil01** [CityOfZion/neon-wallet#1077] opened 2018-05-09 06:54 UTC
**Wallet version or commit SHA:**
0.2.4

**Environment:**
MacOS 10.13.4

**Prerequisites:**
Login with Ledger Nano S.

**Reproduction steps:**
Whenever I want to claim GAS I sign the first transaction on my Ledger, then the claim button grays out and the second transaction never happens.

This has been the case for about 2 weeks now, also on the previous version of the wallet.

**Comment by imolev** [comment] 2018-05-10 10:35
In my case the problem is like this:

Wallet version or commit SHA:
0.2.4

Environment:
Windows 10

Prerequisites:
Login with Ledger Nano S.

Reproduction steps:
Whenever I want to claim GAS I sign the first transaction on my Ledger, then sign the second transaction and get the following error (everything worked well before): "Error: Claiming GAS failed".

**Comment by galadril** [comment] 2018-05-14 16:29
I have the same issue. Can't claim gas already for some time now.

**Comment by IntelligentFunction** [comment] 2018-05-15 15:11
Nope haven't been able to claim gas on the latest version of the neon wallet running Linux Mint. I went back to the last version that I was able to claim gas, but that was back in February, that worked once and then didn't work at all. Back on the latest build and still nothing.

**Comment by drptbl** [comment] 2018-06-05 22:50
Should be fixed with latest release. Please re-open if it's still an issue.

**Closed by drptbl** 2018-06-05 22:50 UTC
