### ISSUE TITLE
neon-wallet

### ISSUE THREAD

**Issue by inderashah007** [CityOfZion/neon-wallet#2337] opened 2021-12-01 20:16 UTC
Please complete the form below. Any issue added that does not include these details will be closed as "not enough information".

For support using the software or concerns about the status of your funds, please go to the #support channel on the NEO Smart Economy Discord Server - https://discord.cityofzion.io

**Wallet version or commit SHA:**
e.g.: 0.2.3 or dcae88c

**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309

**Prerequisites:**
e.g.: Don't have any custom tokens added before running the wallet

**Reproduction steps:**
e.g.:
1. Start Neon Wallet
2. Click on "Manage Neon settings" button
3. Click on "Manage Tokens" button
4. Click on "Add a new token" button

some description (for ex. what happens after completing reproduction steps), e.g.:
After clicking on "Add a new token" button, wallet "hangs" for 2 seconds.

**Screenshots/Video:**
e.g.: https://example.com/screenshot.png

**Comment by Saint0asper** [comment] 2021-12-13 13:22
Hello.
I registered the wallet in 2018 when I was Neo Legacy. Now I have a few Gala tokens there, not much, but I would like to bring them to the Binance exchange.
I have two questions:
1) Does the Neo Legacy work in a Bep20 or erc20 system? Because when transferring to Binance, you need to specify this item.
2) Why can't I transfer tokens anywhere from my wallet? I tried to withdraw to Binance, but I get an error. Then I tried to transfer the wallet to n3 inside the system through migration (because I thought that due to the type of wallet I could not transfer tokens to the exchange), but it also gives an error and it is not possible to transfer tokens.

I would be grateful if someone could explain what to do.

**Comment by tlmatjuda** [comment] 2021-12-19 21:35
Hi Team I have the same problem as @Saint0asper 

Please assist. I tried the Discord server and could not reach it.

**Comment by Saint0asper** [comment] 2021-12-20 07:23
> Привет, команда, у меня та же проблема, что и у @ Saint0asper
> 
> Пожалуйста помогите. Я попробовал сервер Discord и не смог связаться с ним.

**Comment by Saint0asper** [comment] 2021-12-20 07:24
The same problem with discord

**Comment by comountainclimber** [comment] 2021-12-21 15:28
Its unclear to me what the issue is here...  A quick google search shows that the NEO version of GALA has been dead for years at this point => https://www.reddit.com/r/NEO/comments/pomvxr/nep5_gala_token/

It looks like we should remove the pricing portion displayed in the UI to prevent confusion to our users

**Closed as completed by comountainclimber** 2021-12-21 15:28 UTC

**Comment by Saint0asper** [comment] 2021-12-22 11:29
> Мне неясно, в чем проблема ... Быстрый поиск в Google показывает, что версия GALA для NEO уже много лет мертва => [https://www.reddit.com/r/NEO/comments/pomvxr / nep5_gala_token /](https://www.reddit.com/r/NEO/comments/pomvxr/nep5_gala_token/)
> 
> Похоже, нам следует удалить часть цены, отображаемую в пользовательском интерфейсе, чтобы не запутать наших пользователей.

Gala tokens are still traded on the exchange, they are also in the wallet itself, but how to bring them to the exchange?

**Comment by Saint0asper** [comment] 2021-12-22 11:30
> Its unclear to me what the issue is here... A quick google search shows that the NEO version of GALA has been dead for years at this point => https://www.reddit.com/r/NEO/comments/pomvxr/nep5_gala_token/
> 
> It looks like we should remove the pricing portion displayed in the UI to prevent confusion to our users

Gala tokens are still traded on the exchange, they are also in the wallet itself, but how to bring them to the exchange?

**Comment by Saint0asper** [comment] 2021-12-25 09:09
> Its unclear to me what the issue is here... A quick google search shows that the NEO version of GALA has been dead for years at this point => https://www.reddit.com/r/NEO/comments/pomvxr/nep5_gala_token/
> 
> It looks like we should remove the pricing portion displayed in the UI to prevent confusion to our users

In my wallet, it is displayed that the token is alive and its price changes during the day, but I cannot withdraw it to the Binance exchange. It gives me an error like in the screenshot.

What to do about it?
What is the problem and why can't I bring tokens to the exchange?
Also, the token network is not displayed in the wallet: BSC (BEP20) or ETH (ERC20)?
How to bring tokens to the exchange?
![g4URcuLSq2Y](https://user-images.githubusercontent.com/35653714/147381798-e21935e5-dfa6-454d-811f-b2d56c0fa43f.jpg)

**Comment by tlmatjuda** [comment] 2021-12-30 15:56
> 

Sounds like a plan. A minor fix on the UI will help a lot of users, because if GALA is not supported on the NEON app then it should not be displayed. Thanks a lot, team.
