### ISSUE TITLE
Ledger Nano S + Neon 0.1.3 Windows 10 Can't send GAS

### ISSUE THREAD

**Issue by ned-robinson** [CityOfZion/neon-wallet#713] opened 2018-02-15 06:17 UTC
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by ned-robinson** [comment] 2018-02-15 06:17
No answers on Discord. COZ, please respond.

**Comment by GHuser357** [comment] 2018-02-16 03:02
This is not a "general usage" problem, this is a broken wallet problem.

**Comment by mhuggins** [comment] 2018-02-19 15:26
Duplicate of #685.

**Closed by mhuggins** 2018-02-19 15:26 UTC
