### ISSUE TITLE
Neon Wallet screen goes blank after some period of time

### ISSUE THREAD

**Issue by starksm64** [CityOfZion/neon-wallet#1167] opened 2018-05-30 18:52 UTC
**Wallet version or commit SHA:**
0.2.5

**Environment:**
OSX High Sierra 10.13.4 (17E202)

**Prerequisites:**
Have a saved wallet

**Reproduction steps:**
1. Start Neon Wallet
2. Sign into saved wallet
3. Wait, after some unknown time/event, the wallet screen is blank as shown in the screenshot, and the console log shows the indicated errors.

**Screenshots/Video:**
[neon-wallet.log](https://github.com/CityOfZion/neon-wallet/files/2055148/neon-wallet.log)
![neonwallet](https://user-images.githubusercontent.com/332210/40739498-3ad6f500-63fb-11e8-9565-6de6e0da1cf2.png)

Once the screen has gone blank, nothing causes it the screen to refresh. I have tried resizing but that had no effect.

**Comment by evgenyboxer** [comment] 2018-05-31 03:43
Thanks for reporting this bug.
There is a PR for fixing certain connectivity issues (https://github.com/CityOfZion/neon-wallet/pull/1166)

Its not merged yet, but I am curious if this will fix the issue. If you wish to try it, then switch to the branch: `fix-connectivity-issues`

**Comment by drptbl** [comment] 2018-06-02 17:33
Caused by #1129. Will be fixed in next release. Please re-open if not. Thanks.

**Closed by drptbl** 2018-06-02 17:33 UTC

**Comment by tarlig** [comment] 2018-07-09 20:33
Problem still exists in version 0.2.5 on my MacOS High Sierra

**Comment by drptbl** [comment] 2018-07-09 20:39
@tarlig Next release didn't happen yet.
