### ISSUE TITLE
QR codes for public address, encrypted key and private key are missing after creating/importing a new wallet

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1579] opened 2018-10-23 16:31 UTC
**Wallet version or commit SHA:**
`design-v2` branch (9e2d017)

QR codes for public address, encrypted key and private key are missing after creating/importing a new wallet in v2.

**Example:**
![ex](https://user-images.githubusercontent.com/8177587/42729735-0dea4b36-87e2-11e8-9f09-40518350ae81.PNG)

**Comment by drptbl** [comment] 2018-10-25 22:52
Encrypted key QR code is still missing.

**Comment by comountainclimber** [comment] 2018-10-25 22:57
That is by design I am closing this for now...

**Closed by comountainclimber** 2018-10-25 22:57 UTC
Labels: bug, design-v2
