### ISSUE TITLE
Import Whitescreen + token not showing up in 0.2.2 but in 0.1.4

### ISSUE THREAD

**Issue by goldenstar2k** [CityOfZion/neon-wallet#890] opened 2018-03-17 12:22 UTC
i would like to post a bug using the latest 0.2.2. I created 10 neo addresses, exported them into a json. I uninstalled my 0.1.4 + i deleted the neon folder remaining and installed the latest 0.2.2. After importing the json into the neon client the screen remained white. I closed the neon wallet reopened and logged into my account with all my tokens. But its not showing up the tokens. On the 0.1.4 the import of the json and showing up of tokens worked flawless.

**Comment by swolfaardt** [comment] 2018-03-21 12:57
Same problem did you have any tokens? saw someones post saying if it is <0 wont show?

**Comment by drptbl** [comment] 2018-04-09 18:41
Looks like a duplicate of #851.
Also it was already fixed with latest wallet release (0.2.3).

> Bug Fixes:
> ...
> Fixed wallet recovery resulting in white screen (no longer requires app restart).

Regarding tokens.. it's not a bug. You have to add script hashes for tokens first before you can see them. Go to "Manage Neon settings" => "Manage Tokens" and add them there. After that, login to your wallet and you should see your tokens.

**Closed** 2018-04-09 19:53 UTC
