### ISSUE TITLE
Feature: PrivateNet

### ISSUE THREAD

**Issue by belane** [CityOfZion/neon-wallet#1696] opened 2018-11-13 22:50 UTC
Would be great to add PrivateNet to the network menu.

It would allow developers to test their projects with the same tool that the 90% of their future users will use.

**Comment by drptbl** [comment] 2018-11-20 12:29
@belane Looks like a duplicate of #1637. Please correct me if I'm wrong, thanks.

**Closed by drptbl** 2018-11-20 12:29 UTC
