### ISSUE TITLE
Unable to send NEP5 tokens, neither to claim GAS

### ISSUE THREAD

**Issue by P2NPoison** [CityOfZion/neon-wallet#774] opened 2018-02-25 23:39 UTC
## GitHub issues are intended for tracking development tasks, not troubleshooting general usage problems.

**Comment by mhuggins** [comment] 2018-02-27 22:43
Duplicate of #765.

**Closed by mhuggins** 2018-02-27 22:43 UTC

**Comment by P2NPoison** [comment] 2018-02-27 22:44
Why do you close the issue?
The problem is still alive.

**Comment by mhuggins** [comment] 2018-02-27 23:41
Because it's a duplicate.  By opening multiple duplicate issues, it makes it difficult to track specific bugs.  Also, for clarity, this is a bug tracker, not a support tracker.
