### ISSUE TITLE
Implement loading indicator on NEP-9 QR Code (it's loading quite slow leaving blank white space for a while)

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/neon-wallet#1524] opened 2018-10-16 20:20 UTC
**Wallet version or commit SHA:**
`design-v2` branch (a64a531)

**Environment:**
MacBook Pro (13-inch, 2017), macOS Mojave 10.14

**Reproduction steps:**
1. Login to your wallet
2. Click on "Receive" button on the left menu
3. Click on "Request Assets" tab
4. Type any amount of asset to request
5. Click on "Generate Code" button => there is white blank space instead of QR code depending on network connection (takes up to 5 seconds for me)

**Description:**
Implement loading indicator on NEP-9 QR Code (it's loading quite slow leaving blank white space for a while).

**Screenshots/Video:**
https://i.imgur.com/4TNOjZY.gifv
https://i.imgur.com/4eCNJf5.gifv

**Comment by drptbl** [comment] 2018-10-25 22:49
Doesn't work, there is no loading indicator and throws error in console:
<img width="784" alt="screenshot 2018-10-26 at 00 49 05" src="https://user-images.githubusercontent.com/8177587/47534798-fcb36f00-d8b8-11e8-8642-18f322fd4d04.png">

**Comment by ranbena** [comment] 2018-11-11 09:30
If I understand correctly the QR image is generated locally - there's no network request and it shows up instantly for me, no lag no error.

@drptbl can you check if this is perhaps ok now?

**Comment by comountainclimber** [comment] 2019-03-04 15:40
Closing this issue for now - unable to reproduce any issues related to this in 2.1.0... feel free to re open if there is still a problem!

**Closed by comountainclimber** 2019-03-04 15:40 UTC
Labels: enhancement
