### ISSUE TITLE
White screen after using 'MAX' function on send screen [0.0.8]

### ISSUE THREAD

**Issue by Freekje** [CityOfZion/neon-wallet#469] opened 2018-01-04 15:20 UTC
Found replicable issue in 0.0.8 : 

Go to Send , use the 'max' function & select recipient , press send and screen goes white.
Tested this for gas & neo. Manually filling in the max number lets you go to the next page.

**Comment by mhuggins** [comment] 2018-01-04 22:20
Thanks for reporting.  @dvdschwrtz found the cause and is working on a fix.  Stay tuned.

**Comment by evgenyboxer** [comment] 2018-01-07 05:01
This is now fixed on 0.0.9

**Closed by evgenyboxer** 2018-01-07 05:01 UTC
