### ISSUE TITLE
Problems with Neon Wallet /Ledger Nano S . I can not transfer from my NEON wallet RPX to www.kucoin.com

### ISSUE THREAD

**Issue by niker26** [CityOfZion/neon-wallet#510] opened 2018-01-09 20:11 UTC
Dear friends , I have following problem : Yesterday I tried to use NEON WALLET via my Ledger Nano S . I transferred my balance of RED PULSE from www.kucoin.com to Neon Wallet . Today I am trying to do the same exercise in the opposite way from my Neon Wallet to www.kucoin.com. The system does not work . Neon wallet gives me a message to confirm the  transaction . After My confirmation , Neon Wallet gives me a message that will update me when transaction is ready ... It looks OK, but actually there is not a transaction ... My balance stays in Neon Wallet and nothing more happened ....
I tried this exercise 10 times , but without a result ..... 
Could you advice me what to do to transfer my balance of RPX from NEON WALLET to KuCoin ?
I am using the latest versions of NEON WALLET and the NEO app for LEDGER WALLET S .
I have GAS in my NEON WALLET !

Does anybody have met the same situation ??
Thank you in advance !!!

**Comment by JagaB** [comment] 2018-01-10 07:43
I've got exactly the same issue. 

I can't transfer both my RPX and DBC from my Ledger Nano S wallet. Got both the newest versions. Just as Niker26 says, it looks like everything work just fine, but the actual transfer won't execute.  

Please help dear friends.

**Comment by RLEE0731** [comment] 2018-01-11 04:26
Same issue, using 0.0.9 release and 1.1.1 Neo app.

**Comment by sschepis** [comment] 2018-01-15 01:06
Same issue

Neon wallet 0.0.7
Ledger Nano S
OSX 10.10.5

**Comment by navneetlakra** [comment] 2018-01-15 01:07
Down again. 
Neon wallet 0.0.9 
Ledger Nano S 
OSX 10.11.6

**Comment by juanrogersp** [comment] 2018-01-15 04:27
I have the exact same issue when trying to transfer my DBC from the NEON app using my Ledger Nano S to the Kucoin Exchange Wallet for DBC.

I have GAS (about 0.0087)

Ledger Nano S - Version (App 1.1.1)
Neon wallet 0.0.9
OSX 10.13.2

**Comment by ProsperityPro** [comment] 2018-01-17 18:49
Add my name to the list...Please help. any suggestions are appreciated.
NEON is updated, Gas in wallet, going to KUcoin.

**Comment by Jammmmin** [comment] 2018-01-18 20:25
Yup, me too. Neon wallet not working. Block displayed on wallet not in sync with blockchain monitor.

**Comment by Jammmmin** [comment] 2018-01-18 20:30
neon wallet API looks out of sync too....is this the problem?

http://api.neonwallet.com/v2/

![image](https://user-images.githubusercontent.com/35394656/35119880-3e498ff6-fc8e-11e7-8767-63f5890cd38d.png)

**Comment by emeric17** [comment] 2018-01-22 20:45
Hi, I have the same issue but different token. I m tried many times to send some ETH onto Kucoin. Everything is fine onto the ledger, i m getting to confirm the transaction, then a message saying transaction confirmed. But nothing happens. My ETH balance onto Nano Ledger S stays the same. Tried to send onto Binance, nothing is happening. I downloaded the logs from Nano Ledger, I can see all my failed attempt. Is it ETH down ? or kucoin ?

**Comment by stevesbrain** [comment] 2018-01-22 22:49
@emeric17 Wrong support channel - this is for NEO, not ETH :)

**Comment by joeman205** [comment] 2018-01-24 22:31
Same issue with. I can transfer it TO my ledger nano but not FROM my ledger to anywhere else

**Comment by Marto15** [comment] 2018-01-27 06:59
Any way around this peeps? Quite fristrating

**Comment by Marto15** [comment] 2018-01-27 10:11
Yeh trying to send RPX too exchange for desperate ethereal transfers, need some money for ico, if this could be rectified asap that'd be fantastic

**Comment by esheds** [comment] 2018-01-29 15:32
same here....cant transfer of claim gas....

**Comment by joeman205** [comment] 2018-01-29 23:32
Still not working ladies and gents. All I want to do is move my GAS from my ledger nano s to binance. Anyone know how to do this??  Thanks!

**Comment by JoeyVV** [comment] 2018-02-01 20:49
Hi Guys, I'm having the same issues with withdrawal my RPX to kucoin. Seems that nobody knows what to do or solve this problem.
Hope we can fix this together and if somebody knows what to do please let us know!!

**Comment by numero41** [comment] 2018-02-01 20:59
https://github.com/CityOfZion/neon-wallet/issues/524

**Comment by zulfh** [comment] 2018-02-03 15:41
Guys I am having the same issue. I transferred NEO to kucoin from neon wallet and I don't see it in kucoin yet. It's been 1 hour. I was able to successfully transfer from Kucoin to neon though. Anyone else have the same issue ?

**Comment by KingVerso** [comment] 2018-02-06 11:42
Same here....trying to deposit TKY to kucoin using neon 0.1.2 and it's not working (I am using a ledger nano s)

**Comment by Boobybandit** [comment] 2018-02-06 14:30
Hi guys, just wanted to give an update on using the Neon wallet (v1.1.2) and Ledger. I succesfully transferred RPX from Kucoin and huobi to the Neon wallet (connected through Neo app on ledger), and I send some RPX back to kucoin and then withdrew again. Just wanted to post this update because last week my RPX was not visible in the Neon wallet (only Neoscan.io), and I could also not send RPX.

**Closed** 2018-02-11 22:24 UTC
