### ISSUE TITLE
Plans to update Neon ahead of Red Pulse ICO

### ISSUE THREAD

**Issue by fc0712** [CityOfZion/neon-wallet#195] opened 2017-09-26 07:30 UTC
Hey.

Does you guys have any plan to update the Neon Wallet ahead of the Red Pulse ICO? 

Thanks in advance :)

**Comment by Satoshinaire** [comment] 2017-09-26 19:50
This is a duplicate of #145, to be addressed in #146.

**Comment by Ejhfast** [comment] 2017-10-11 00:10
We did :)

**Closed by Ejhfast** 2017-10-11 00:10 UTC
