### ISSUE TITLE
Still Can't Send GAS. V0.1.4 This Version DOES NOT FIX THIS ISSUE.

### ISSUE THREAD

**Issue by ned-robinson** [CityOfZion/neon-wallet#734] opened 2018-02-19 06:16 UTC

**Comment by ned-robinson** [comment] 2018-02-19 06:18
Stop telling me to go to the Discord group. YOU IGNORE THAT GROUP JUST LIKE YOU IGNORE THIS.

**SENDING GAS from NANO LEDGER S STILL DOES NOT WORK. WHEN ARE YOU GOING TO FIX IT?**

**Comment by mhuggins** [comment] 2018-02-19 15:25
Duplicate of #713.

**Closed by mhuggins** 2018-02-19 15:25 UTC
