### ISSUE TITLE
Can't send GAS, Ledger Nano s 0.1.4

### ISSUE THREAD

**Issue by ergofredo** [CityOfZion/neon-wallet#782] opened 2018-02-28 16:15 UTC
No device confirmation appearing on the device which makes the outbound tx fail. 

Ledger nano S  firmware 1.3
Neon 0.1.4 Windows

**Comment by mhuggins** [comment] 2018-02-28 16:16
Duplicate of #685.

**Closed by mhuggins** 2018-02-28 16:16 UTC
