### ISSUE TITLE
Add Recipient button should be active until the limit

### ISSUE THREAD

**Issue by osmirnov** [CityOfZion/neon-wallet#1664] opened 2018-11-10 19:46 UTC
**Wallet version or commit SHA:**
2.0.0.dev (be831ac7)

**Environment:**
e.g.: Win 10 Pro (64 bit) Version 10.0.17134 Build 17134

**Prerequisites:**
N/A

**Reproduction steps:**
1. Start Neon Wallet
2. Login
3. Open "Send" page -> "Add Recipient" button is inactive

Expectation: "Add Recipient" button has to be active on page load. A user can add many recipients and fill them after.

**Screenshots/Video:**
![image](https://user-images.githubusercontent.com/454196/48305375-59d53480-e4f7-11e8-9ace-393eeb34a7e5.png)

**Comment by comountainclimber** [comment] 2018-11-10 21:53
This component used to be set up how you were suggesting however others thought it should be disabled until each row is filled out... I personally dont care but this is not really a bug - maybe we should add a tooltip over the disabled button?

**Comment by osmirnov** [comment] 2018-11-10 22:16
I see no harm to show it as active. It allows a user to pick what they want to do first "start filling recipients one after one" or "add how many they want and fill after".

**Comment by comountainclimber** [comment] 2018-11-27 05:02
Closing this for now as the current implementation is by design... Will reopen if there is activity here or others feel strongly

**Closed by comountainclimber** 2018-11-27 05:02 UTC
