### ISSUE TITLE
Version Warning

### ISSUE THREAD

**Issue by DaveAuld** [CityOfZion/neon-wallet#162] opened 2017-09-07 17:14 UTC
The version 'out of date' warning in Version 0.0.4 asks you to install version 0.0.4, i.e. it asks you to install the same version number.

Don't know about the Version 0.0.5 release.....

![image](https://user-images.githubusercontent.com/4674288/30175897-1baf3146-9409-11e7-9819-680cfb8f6c66.png)

**Comment by Satoshinaire** [comment] 2017-09-07 17:53
This was fixed in 0.0.5 once you update 😄 

Duplicate of #159.

**Comment by W-Lyf** [comment] 2017-09-07 18:15
Good, thanks for looking into that.

**Closed** 2017-09-08 19:47 UTC
