### ISSUE TITLE
Unable to load

### ISSUE THREAD

**Issue by foochuanyue** [CityOfZion/neon-wallet#1980] opened 2020-08-31 08:38 UTC
My token Balances and System assets just show. "Failed to load. Retry or select a different node"

**Comment by tomasdev** [comment] 2020-11-24 15:22
Duplicate of #1989 -- should be fixed now.

**Comment by comountainclimber** [comment] 2020-12-01 01:42
https://github.com/CityOfZion/neon-wallet/pull/2028

**Closed by comountainclimber** 2020-12-01 01:42 UTC
