### ISSUE TITLE
Neon Wallet 0.1.2 (and previous versions) - Can't claim GAS

### ISSUE THREAD

**Issue by derwen** [CityOfZion/neon-wallet#660] opened 2018-02-06 14:22 UTC
It's actually an issue for me since a few previous versions, I am not able to claim gas for weeks now. Everything else works normally, sending NEO and tokens, but when I claim gas and sign the first transaction it either fails or when "sign second transaction" comes on Neon, nothing happens on Ledger - it's stuck on "Wake up NEO". Tried reinstalling Neon, tried multiple Neon versions, tried reinstalling NEO app on ledger. Nothing works. Have quite a few GAS stuck by now. Solution? Thanks.

Guys from Ledger have no clue, they sent me here.

**Comment by ned-robinson** [comment] 2018-02-13 07:14
Why is this closed? The bug still exists. It should not be closed until it is fixed.

**Comment by reductionista** [comment] 2018-02-18 19:45
I'm having the same issue.  All transactions work, but I can't claim gas.  Using Ledger Nano S, OSX

**Comment by mhuggins** [comment] 2018-02-18 21:00
@ned-robinson It's not closed.  You might be looking at a different issue that was closed because it's a duplicate of this one.

**Comment by reductionista** [comment] 2018-02-18 21:37
I just updated to 0.1.3 and it fixed the problem.

**Comment by derwen** [comment] 2018-02-20 14:42
I updated to 0.1.3 and 0.1.4 and it did not fix the problem.

**Comment by tgwttihs** [comment] 2018-02-21 10:00
I can't claim gas either... been using all versions. Sometimes it works, most times, it doesn't...

**Comment by brianlenz** [comment] 2018-02-21 19:32
If you're still having issues claiming GAS on your Ledger with Neon 0.1.4, make sure you are running the latest version 1.1.1 of the Ledger Neo app:

https://support.ledgerwallet.com/hc/en-us/articles/115005530425-How-to-install-and-use-Neo-NEO-

You need to delete the current Neo app from your Ledger (using the Ledger Manager Chrome app) and reinstall in order to complete the upgrade.

**Comment by derwen** [comment] 2018-02-21 22:01
Do you even read the messages you are replying to?

Tried it. Doesn't work. Wrote about it in the original post.

**Comment by ned-robinson** [comment] 2018-02-22 06:16
**I've been able to fix the issue myself. Here's what I did:**

•    From NEON wallet, go to Manage Neon settings
•    Exported Wallet Recovery File
•    Then immediately, load Wallet Recovery File (pick the one you just exported)
•    Opened Nano Ledger in NEON
o    Sent 0.000001 to non-ledger private wallet – Worked!
o    Sent 1.0 to non-ledger private wallet – Didn’t work
o    Sent 0.000009 to non-ledger private wallet – Worked!
o    Sent 0.999999 to non-ledger private wallet – Worked but only sent 0.9. The ending decimals weren’t sent, dropped from transaction.

Oberservations
1.    There is sometimes a noticeable delay between getting the Sign Transaction in the NEON wallet and the Sign Transaction coming up on the NANO Ledger. One time it took over 30 seconds. So the NEON wallet thought the transaction failed but then the message showed up on the NANO Ledger. I had to close down the NEON WALLET to get things back in sync. (Did not have to reboot).
2.    Decimals after the 2nd place are getting truncated and removed from the send. Most of the time, not 100% of the time. 
3.    Very inconsistent experience sending GAS.
4.    Not sure if exporting and then importing the wallet recovery file did anything but it was after doing it that I got some success. Maybe something was corrupted that the recovery file cleared out?

In any case, I can now send GAS from the NEON wallet.

**Comment by derwen** [comment] 2018-02-22 07:37
My issue is not that I can't send GAS. I can. I can't CLAIM gas.

**Comment by derwen** [comment] 2018-02-22 13:24
So once again.....

So once again:
1. Claim GAS
2. Asked to Sign transaction 1 of 2, I sign it
3. Waiting for transaction to clear...
4. Sign transaction 2 of 2 to claim GAS --> shows up briefly, for maybe half a second (but nothing happens on Ledger, stays on "Wake up NEO"
5. Error Claim failed immediately shows up

![neo gas issue](https://user-images.githubusercontent.com/32641583/36540814-149ce7ca-17dc-11e8-9e4b-4c10ed062f4c.jpg)

**Comment by mhuggins** [comment] 2018-04-30 17:26
This issue should be fixed in [version 0.2.4](https://github.com/CityOfZion/neon-wallet/releases/tag/0.2.4).

**Closed by mhuggins** 2018-04-30 17:26 UTC
